import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/NavBar";
import Provider from "@/providers/authProvider";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata: Metadata = {
	title: "Gadgets App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${poppins.className}w-full min-h-screen flex flex-col  `}>
				<Provider>
					<NavBar />
					<main className=" flex-grow">{children}</main>
				</Provider>
			</body>
		</html>
	);
}
